//! Cross-crate feedback test for the EGRI knowledge calibration loop.
//!
//! The promotion payload is generated by `lago-knowledge` and consumed by the
//! Autonomic projection/rule path. This guards the seam between calibration,
//! production config promotion, and rollback advisories.

use aios_protocol::event::EventKind;
use autonomic_controller::{KnowledgeRegressionRule, fold};
use autonomic_core::events::AutonomicEvent;
use autonomic_core::gating::HomeostaticState;
use autonomic_core::rules::HomeostaticRule;
use lago_core::EventPayload;
use lago_knowledge::{
    KnowledgePromotionRecord, KnowledgePromotionRequest, KnowledgeThresholdArtifact,
    promote_to_lago_toml,
};
use tempfile::TempDir;

#[test]
fn promoted_knowledge_config_feeds_autonomic_regression_rollback() {
    let tmp = TempDir::new().unwrap();
    let config_path = tmp.path().join("lago.toml");

    promote_to_lago_toml(
        &config_path,
        &KnowledgePromotionRequest::new(
            KnowledgeThresholdArtifact::default(),
            "trial-001",
            0.70,
            0.78,
        )
        .with_promoted_at("2026-04-08T12:00:00Z"),
    )
    .unwrap();

    let promoted_artifact = KnowledgeThresholdArtifact {
        health_threshold: 0.75,
        hybrid_keyword_boost: 0.35,
        ..KnowledgeThresholdArtifact::default()
    };
    let promoted_record = promote_to_lago_toml(
        &config_path,
        &KnowledgePromotionRequest::new(promoted_artifact, "trial-020", 0.78, 0.86)
            .with_promoted_at("2026-04-09T12:00:00Z"),
    )
    .unwrap();

    assert_eq!(promoted_record.version, "v2");
    assert_eq!(promoted_record.rollback_target.as_deref(), Some("v1"));

    let mut state = HomeostaticState::for_agent("knowledge-calibration");
    state = fold(state, &promotion_kind(&promoted_record), 1, 1_000);

    for i in 0..4 {
        state = fold(
            state,
            &EventKind::KnowledgeEvaluated {
                health_score: 0.70,
                note_count: 50,
                contradictions: 0,
                missing_pages: 0,
                orphans: 0,
            },
            i + 2,
            1_100 + (i * 100),
        );
    }

    let decision = KnowledgeRegressionRule::default()
        .evaluate(&state)
        .expect("sustained post-promotion regression should request rollback");

    assert!(decision.rationale.contains("post-promotion regression"));
    assert!(decision.restrict_side_effects.unwrap_or(false));
    assert!(decision.advisory_events.iter().any(|event| matches!(
        event,
        AutonomicEvent::RollbackRequested {
            artifact,
            rollback_to,
            ..
        } if artifact == "knowledge_thresholds" && rollback_to == "v1"
    )));
}

fn promotion_kind(record: &KnowledgePromotionRecord) -> EventKind {
    match record.event_payload() {
        EventPayload::Custom { event_type, data } => EventKind::Custom { event_type, data },
        other => panic!("expected custom promotion payload, got {other:?}"),
    }
}
