//! Wire contract for the lifed kernel daemon.
//!
//! Generated code lands in the [`pb`] module (Commit 3 of BRO-857). This
//! crate will also expose `From` / `TryFrom` bridges between generated proto
//! messages and `aios_protocol` canonical types once codegen is wired.

#![deny(unsafe_code)]

/// Placeholder — generated by `build.rs` in Commit 3 of BRO-857.
pub mod pb {}
